
services:
- docker
  
go:
- master

branches:
  only:
  - /^v\d+\.\d+\.\d+$/

jobs:
  include:
    
    - name: build and deploy binaries
      script:
        - go get github.com/mitchellh/gox
        - go get -d
        - gox -os="linux darwin" -arch="amd64" -verbose -output="bin/{{.Dir}}_{{.OS}}_{{.Arch}}"
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: "$GITHUBTOKEN"
        file_glob: true
        file: bin/*
        on:
          tags: true
    - name: Build and deploy docker image
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t claranet/rubrik-exporter:latest .
        - docker tag claranet/rubrik-exporter:latest claranet/rubrik-exporter:$TRAVIS_BRANCH
        - docker push claranet/rubrik-exporter:latest
        - docker push claranet/rubrik-exporter:$TRAVIS_BRANCH
