{
 "title": "Rubrik Backup",
 "tags": [
  "rubrik",
  "backup"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "archive",
    "label": "Archive",
    "query": "label_values(rubrik_archive_location_status , name)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "#VM Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(rubrik_vm_protected)" }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(rubrik_system_storage_used)*100 / rubrik_system_storage_total"
    }
   ]
  },
  {
   "title": "#Briks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count by(brik) (rubrik_count_nodes))"
    }
   ]
  },
  {
   "title": "Rubrik Ingestion Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rubrik_system_physical_ingest_bytes",
     "legendFormat": "Rubrik Ingestion Throughput"
    }
   ]
  },
  {
   "title": "Runaway Remaining",
   "type": "singlestat",
   "description": "Get the number of days remaining before the system fills up.",
   "gridPos": { "h": 2, "w": 4, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "rubrik_stat_runaway_remaining" }
   ]
  },
  {
   "title": "#Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(rubrik_count_nodes)" }
   ]
  },
  {
   "title": "AVG Growth / day",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "rubrik_stat_average_storage_growth_per_day"
    }
   ]
  },
  {
   "title": "#VM Not Protected",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(rubrik_vm_protected == 0)"
    }
   ]
  },
  { "title": "Rubrik", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rubrik_node_network_received*8)",
     "legendFormat": "Total Received"
    },
    {
     "expr": "sum(rubrik_node_network_transmitted*8)",
     "legendFormat": "Total Transmitted"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "rubrik_system_storage_snapshot", "legendFormat": "Snapshot" },
    {
     "expr": "rubrik_system_storage_miscellaneous",
     "legendFormat": "System"
    },
    {
     "expr": "rubrik_system_storage_live_mount",
     "legendFormat": "Live Mount"
    }
   ]
  },
  { "title": "Archive - $archive", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "archive" },
  {
   "title": "Bandwith",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rubrik_archive_storage_bandwidth{name=\"$archive\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Storage usage of Archive",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rubrik_archive_storage_data_archived{name=\"$archive\"}",
     "legendFormat": "Data on Archive {{name}}"
    },
    {
     "expr": "sum(rubrik_archive_storage_archived_vm{name=\"$archive\"})",
     "legendFormat": "#VM in Archive {{name}}"
    }
   ]
  }
 ]
}